begin;

truncate table public.project_skill_tags, public.projects, public.skills, public.timeline_entries, public.persona_recommendations, public.personas, public.content_items, public.media restart identity cascade;

insert into public.media (slug, label, media_kind, source_type, local_source_path, storage_bucket, storage_path, external_url, mime_type, alt_text) values
('asset-driving', 'Driving Simulator', 'image', 'storage', 'src/assets/driving.png', 'portfolio-public', 'assets/driving.png', null, 'image/png', 'Driving Simulator'),
('asset-mrElectronics', 'MR BTECH Electronics Training Modules', 'image', 'storage', 'src/assets/mr_electronics.png', 'portfolio-public', 'assets/mr_electronics.png', null, 'image/png', 'MR BTECH Electronics Training Modules'),
('asset-lathe', 'VR Lathe Machine Training', 'image', 'storage', 'src/assets/lathe.png', 'portfolio-public', 'assets/lathe.png', null, 'image/png', 'VR Lathe Machine Training'),
('asset-crane', 'Crane Simulator', 'image', 'storage', 'src/assets/crane.jpg', 'portfolio-public', 'assets/crane.jpg', null, 'image/jpeg', 'Crane Simulator'),
('asset-weldingAdvanced', 'Advanced VR Welding Simulator', 'image', 'storage', 'src/assets/welding_advanced.png', 'portfolio-public', 'assets/welding_advanced.png', null, 'image/png', 'Advanced VR Welding Simulator'),
('asset-fire', 'Fire Safety Training', 'image', 'storage', 'src/assets/fire.jpg', 'portfolio-public', 'assets/fire.jpg', null, 'image/jpeg', 'Fire Safety Training'),
('asset-screw', 'Screwing Process Training', 'image', 'storage', 'src/assets/screw.jpeg', 'portfolio-public', 'assets/screw.jpeg', null, 'image/jpeg', 'Screwing Process Training'),
('asset-terminal', 'Terminal Fixing', 'image', 'storage', 'src/assets/terminal.jpeg', 'portfolio-public', 'assets/terminal.jpeg', null, 'image/jpeg', 'Terminal Fixing'),
('asset-safe', 'Holder Fixing', 'image', 'storage', 'src/assets/safe.jpeg', 'portfolio-public', 'assets/safe.jpeg', null, 'image/jpeg', 'Holder Fixing'),
('asset-dieCasting', 'UNO Minda Die Casting Training', 'image', 'storage', 'src/assets/die_casting.png', 'portfolio-public', 'assets/die_casting.png', null, 'image/png', 'UNO Minda Die Casting Training'),
('asset-leakageTesting', 'UNO Minda Leakage Testing', 'image', 'storage', 'src/assets/leakage_testing.png', 'portfolio-public', 'assets/leakage_testing.png', null, 'image/png', 'UNO Minda Leakage Testing'),
('asset-painting', 'UNO Minda Painting Process', 'image', 'storage', 'src/assets/painting.png', 'portfolio-public', 'assets/painting.png', null, 'image/png', 'UNO Minda Painting Process'),
('asset-pdi', 'UNO Minda PDI Inspection', 'image', 'storage', 'src/assets/pdi.png', 'portfolio-public', 'assets/pdi.png', null, 'image/png', 'UNO Minda PDI Inspection'),
('asset-plugin', 'UNO Minda Plug-In Process', 'image', 'storage', 'src/assets/plugin.png', 'portfolio-public', 'assets/plugin.png', null, 'image/png', 'UNO Minda Plug-In Process'),
('asset-vmc', 'UNO Minda VMC Operation', 'image', 'storage', 'src/assets/vmc.png', 'portfolio-public', 'assets/vmc.png', null, 'image/png', 'UNO Minda VMC Operation'),
('asset-chess', '3D Chess Game', 'image', 'storage', 'src/assets/chess.png', 'portfolio-public', 'assets/chess.png', null, 'image/png', '3D Chess Game'),
('asset-tagoreHostel', 'Tagore Hostel (FPS Game)', 'image', 'storage', 'src/assets/tagoreHostel.png', 'portfolio-public', 'assets/tagoreHostel.png', null, 'image/png', 'Tagore Hostel (FPS Game)'),
('asset-plusOneDimension', '+1 Dimension', 'image', 'storage', 'src/assets/+1Dimension.png', 'portfolio-public', 'assets/+1Dimension.png', null, 'image/png', '+1 Dimension'),
('asset-amMusic', 'Spotify Clone', 'image', 'storage', 'src/assets/AM Music.png', 'portfolio-public', 'assets/AM Music.png', null, 'image/png', 'Spotify Clone'),
('asset-ihub', 'IIT Jodhpur Navigational Mapping', 'image', 'storage', 'src/assets/ihub.png', 'portfolio-public', 'assets/ihub.png', null, 'image/png', 'IIT Jodhpur Navigational Mapping'),
('asset-quizGame', 'Quiz Game', 'image', 'storage', 'src/assets/quiz_game.jpg', 'portfolio-public', 'assets/quiz_game.jpg', null, 'image/jpeg', 'Quiz Game'),
('asset-flappyBird', 'Flappy Bird', 'image', 'storage', 'src/assets/flappy_bird.jpg', 'portfolio-public', 'assets/flappy_bird.jpg', null, 'image/jpeg', 'Flappy Bird'),
('asset-atomicHabits', 'Atomic Habits', 'image', 'storage', 'src/assets/atomicHabits.jpg', 'portfolio-public', 'assets/atomicHabits.jpg', null, 'image/jpeg', 'Atomic Habits'),
('asset-richDadPoorDad', 'Rich Dad Poor Dad', 'image', 'storage', 'src/assets/richDadPoorDad.jpg', 'portfolio-public', 'assets/richDadPoorDad.jpg', null, 'image/jpeg', 'Rich Dad Poor Dad'),
('asset-songOfIceAndFire', 'A Song of Ice and Fire', 'image', 'storage', 'src/assets/A Song of Ice and Fire.jpg', 'portfolio-public', 'assets/A Song of Ice and Fire.jpg', null, 'image/jpeg', 'A Song of Ice and Fire'),
('asset-harryPotter', 'Harry Potter', 'image', 'storage', 'src/assets/Harry Potter.jpg', 'portfolio-public', 'assets/Harry Potter.jpg', null, 'image/jpeg', 'Harry Potter'),
('asset-blue', 'recruiter avatar', 'image', 'storage', 'src/assets/blue.png', 'portfolio-public', 'assets/blue.png', null, 'image/png', 'recruiter avatar'),
('persona-recruiter-background', 'recruiter background', 'gif', 'external', null, null, null, 'https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOTZ5eWwwbjRpdWM1amxyd3VueHhteTVzajVjeGZtZGJ1dDc4MXMyNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9dg/16u7Ifl2T4zYfQ932F/giphy.gif', null, 'recruiter background'),
('asset-grey', 'developer avatar', 'image', 'storage', 'src/assets/grey.png', 'portfolio-public', 'assets/grey.png', null, 'image/png', 'developer avatar'),
('persona-developer-background', 'developer background', 'gif', 'external', null, null, null, 'https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNGNidDl5emZpejY2eGFxa2I4NW0zZGNpbWRlbnBrZ3N2dWhhbzM1MyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/TFPdmm3rdzeZ0kP3zG/giphy.gif', null, 'developer background'),
('asset-red', 'stalker avatar', 'image', 'storage', 'src/assets/red.png', 'portfolio-public', 'assets/red.png', null, 'image/png', 'stalker avatar'),
('persona-stalker-background', 'stalker background', 'gif', 'external', null, null, null, 'https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExc28yMjMyZmJ6eWtxbmNwdDV6cXk4dWZmcjFhZms2cXBjN2h5ZDJjeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/QjZXUBUr89CkiWLPjL/giphy.gif', null, 'stalker background'),
('asset-yellow', 'adventurer avatar', 'image', 'storage', 'src/assets/yellow.png', 'portfolio-public', 'assets/yellow.png', null, 'image/png', 'adventurer avatar'),
('persona-adventurer-background', 'adventurer background', 'gif', 'external', null, null, null, 'https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbmxib24ycWo2cjlmazh0NGV5NTZ2Mzd2YWY0M2tvam9oYXBwYW1ocCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ERKMnDK6tkzJe8YVa3/giphy-downsized-large.gif', null, 'adventurer background'),
('recommendation-top_picks-recruiter-0', 'Skills top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/skills/250/200', null, 'Skills'),
('recommendation-top_picks-recruiter-1', 'Experience top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/workexperience/250/200', null, 'Experience'),
('recommendation-top_picks-recruiter-2', 'Projects top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/projects/250/200', null, 'Projects'),
('recommendation-top_picks-recruiter-3', 'Contact Me top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/contact/250/200', null, 'Contact Me'),
('recommendation-top_picks-recruiter-4', 'Let''s Play top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/game/250/200', null, 'Let''s Play'),
('recommendation-top_picks-developer-0', 'Skills top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/coding/250/200', null, 'Skills'),
('recommendation-top_picks-developer-1', 'Projects top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/development/250/200', null, 'Projects'),
('recommendation-top_picks-developer-2', 'Experience top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/work/250/200', null, 'Experience'),
('recommendation-top_picks-developer-3', 'Contact Me top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/connect/250/200', null, 'Contact Me'),
('recommendation-top_picks-developer-4', 'Let''s Play top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/chess/250/200', null, 'Let''s Play'),
('recommendation-top_picks-stalker-0', 'Contact Me top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/call/250/200', null, 'Contact Me'),
('recommendation-top_picks-stalker-1', 'Projects top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/planning/250/200', null, 'Projects'),
('recommendation-top_picks-stalker-2', 'Experience top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/resume/250/200', null, 'Experience'),
('recommendation-top_picks-stalker-3', 'Let''s Play top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/shooter/250/200', null, 'Let''s Play'),
('recommendation-top_picks-adventurer-0', 'Music top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/music/250/200', null, 'Music'),
('recommendation-top_picks-adventurer-1', 'Projects top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/innovation/250/200', null, 'Projects'),
('recommendation-top_picks-adventurer-2', 'Reading top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/books/250/200', null, 'Reading'),
('recommendation-top_picks-adventurer-3', 'Contact Me top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/connect/250/200', null, 'Contact Me'),
('recommendation-top_picks-adventurer-4', 'Let''s Play top_picks image', 'image', 'external', null, null, null, 'https://picsum.photos/seed/space/250/200', null, 'Let''s Play'),
('recommendation-continue_watching-default-0', 'Music continue_watching image', 'image', 'external', null, null, null, 'https://picsum.photos/id/1025/300/200', null, 'Music'),
('recommendation-continue_watching-default-1', 'Reading continue_watching image', 'image', 'external', null, null, null, 'https://picsum.photos/id/1026/300/200', null, 'Reading'),
('recommendation-continue_watching-default-2', 'Contact Me continue_watching image', 'image', 'external', null, null, null, 'https://picsum.photos/id/1029/300/200', null, 'Contact Me'),
('recommendation-continue_watching-stalker-0', 'Reading continue_watching image', 'image', 'external', null, null, null, 'https://picsum.photos/id/1026/300/200', null, 'Reading'),
('recommendation-continue_watching-stalker-1', 'Contact Me continue_watching image', 'image', 'external', null, null, null, 'https://picsum.photos/id/1029/300/200', null, 'Contact Me');

insert into public.skills (slug, name, category, description, icon_key, sort_order) values
('unity-3d', 'Unity 3D', 'Game Development', 'A versatile platform for creating 3D and 2D games.', 'FaGamepad', 0),
('c-sharp', 'C#', 'Programming Languages', 'A powerful language for building games and applications.', 'FaCode', 1),
('kotlin', 'Kotlin', 'Mobile Development', 'A modern language for Android app development.', 'FaAndroid', 2),
('api', 'API', 'Mobile Development', 'Integrating third-party services for enhanced app functionality.', 'FaNetworkWired', 3),
('jetpack-compose', 'Jetpack Compose', 'Mobile Development', 'A modern toolkit for building native Android UIs.', 'FaAndroid', 4),
('exoplayer', 'ExoPlayer', 'Mobile Development', 'A media playback library for Android.', 'FaPlayCircle', 5),
('retrofit', 'Retrofit', 'Mobile Development', 'A type-safe HTTP client for Android.', 'FaNetworkWired', 6),
('firebase', 'Firebase', 'Mobile Development', 'A suite of tools for app development and analytics.', 'FaCloud', 7),
('hilt', 'Hilt', 'Mobile Development', 'A dependency injection library for Android apps.', 'FaTools', 8),
('paging-3', 'Paging 3', 'Mobile Development', 'A library for efficient data loading in Android apps.', 'FaStream', 9),
('blender', 'Blender', '3D Modeling', 'A 3D modeling and animation software.', 'FaCube', 10),
('substance-painter', 'Substance Painter', '3D Modeling', 'A texturing tool for 3D assets.', 'FaPalette', 11),
('dot-net', '.NET', 'Software Development', 'A framework for building robust backend applications.', 'FaWindows', 12),
('unity-netcode', 'Unity Netcode', 'Game Development', 'Designing games that support multiple players.', 'FaUsers', 13),
('server-client', 'Server-Client', 'Software Development', 'Designing robust server-client communication models.', 'FaServer', 14),
('aws', 'AWS', 'Software Development', 'Amazon Web Services for scalable cloud solutions.', 'FaCloud', 15),
('xr-interactions', 'XR Interactions', 'Game Development', 'Creating immersive XR experiences.', 'FaVrCardboard', 16),
('vr-mechanics', 'VR Mechanics', 'Game Development', 'Designing mechanics for virtual reality environments.', 'FaVrCardboard', 17),
('figma-canva', 'Figma Canva', 'Tools', 'Creating intuitive and engaging user interfaces.', 'FaPencilRuler', 18),
('coroutines', 'Coroutines', 'Mobile Development', 'Efficiently managing asynchronous tasks in Kotlin.', 'FaClock', 19),
('game-mechanics', 'Game Mechanics', 'Game Development', 'Designing engaging and interactive gameplay mechanics.', 'FaGamepad', 20),
('git-github', 'Git & GitHub', 'Tools', 'Version control and collaboration tools.', 'FaGithub', 21),
('html-css', 'HTML & CSS', 'Web Development', 'Building responsive and accessible web pages.', 'FaHtml5', 22),
('three-js', 'Three.js', 'Web Development', 'Experience in creating 3D web applications using Three.js.', 'FaCube', 23),
('react', 'React', 'Web Development', 'A JavaScript library for building user interfaces.', 'FaReact', 24),
('javascript', 'JavaScript', 'Programming Languages', 'A versatile language for building web applications.', 'FaJs', 25),
('python', 'Python', 'Programming Languages', 'Extensive experience in machine learning, data analysis, and scripting.', 'FaPython', 26),
('c-plus-plus', 'C++', 'Programming Languages', 'Used for high-performance applications and competitive programming.', 'FaCode', 27),
('c', 'C', 'Programming Languages', 'Foundation of programming with experience in systems development.', 'FaCuttlefish', 28),
('flutter', 'Flutter', 'Mobile Development', 'Proficient in building cross-platform applications using Flutter', 'FaMobileAlt', 29),
('dart', 'Dart', 'Programming Languages', 'Used alongside Flutter for efficient app development', 'FaCode', 30),
('netlify', 'Netlify', 'Software Development', 'Frontend Deployment Platform', 'FaCode', 31);

insert into public.projects (slug, title, description, image_media_id, github_url, youtube_video_id, sort_order) values
('driving-simulator', 'Driving Simulator', 'Developed a VR-based driving simulator for training purposes using Unity. The simulator includes realistic vehicle physics, traffic environments, and user interaction through VR controllers for immersive driving practice.', (select id from public.media where slug = 'asset-driving'), 'https://github.com/aditya29mishra/car-simulator', null, 0),
('mr-btech-electronics-training-modules', 'MR BTECH Electronics Training Modules', 'Developed mixed reality (MR) training modules for B.Tech electronics students, enabling interactive learning of electronic components, circuits, and lab procedures through immersive visualization.', (select id from public.media where slug = 'asset-mrElectronics'), null, 'BGQeamOWpto', 1),
('vr-lathe-machine-training', 'VR Lathe Machine Training', 'Developed an immersive VR lathe machine simulator to train users on machining operations including cutting, shaping, and finishing processes with realistic machine controls and safety procedures.', (select id from public.media where slug = 'asset-lathe'), 'https://github.com/aditya29mishra/lath-main', 'dvt7lDIhXM0', 2),
('crane-simulator', 'Crane Simulator', 'Designed a virtual reality crane operation simulator allowing users to learn safe crane handling, load lifting, and positioning techniques within a simulated industrial environment.', (select id from public.media where slug = 'asset-crane'), null, 'dkbr6-Xl2bI', 3),
('advanced-vr-welding-simulator', 'Advanced VR Welding Simulator', 'A highly detailed VR welding training simulator featuring realistic welding physics, multiple welding techniques, material interaction, and safety training for industrial applications.', (select id from public.media where slug = 'asset-weldingAdvanced'), null, 'JqyANAGsmrM', 4),
('fire-safety-training', 'Fire Safety Training', 'A VR module that simulates emergency fire scenarios, teaching users how to identify hazards, use fire extinguishers, and safely evacuate through guided training steps.', (select id from public.media where slug = 'asset-fire'), null, 'MjWuah5y4wQ', 5),
('screwing-process-training', 'Screwing Process Training', 'An interactive training experience where users learn and perform step-by-step screwing operations using virtual tools in a controlled, immersive environment.', (select id from public.media where slug = 'asset-screw'), null, null, 6),
('terminal-fixing', 'Terminal Fixing', 'This module trains users on correctly placing and securing terminal components in assemblies processes, ensuring precision and safety during the process.', (select id from public.media where slug = 'asset-terminal'), null, null, 7),
('holder-fixing', 'Holder Fixing', 'A VR simulation focused on fixing holders into Workpiece, guiding users through part handling, alignment, and secure fitting procedures.', (select id from public.media where slug = 'asset-safe'), null, null, 8),
('uno-minda-die-casting-training', 'UNO Minda Die Casting Training', 'A VR industrial training module that teaches operators the die casting process including material handling, mold operation, and safety procedures inside a simulated manufacturing environment.', (select id from public.media where slug = 'asset-dieCasting'), null, 'uUNEoHJALEo', 9),
('uno-minda-leakage-testing', 'UNO Minda Leakage Testing', 'A VR training module designed to teach operators how to perform leakage testing procedures on casting components, identify defects, and safely operate leakage testing machines.', (select id from public.media where slug = 'asset-leakageTesting'), null, '8dG_NnXF7xQ', 10),
('uno-minda-painting-process', 'UNO Minda Painting Process', 'Simulates the industrial painting workflow for casting components, training operators on proper handling, coating procedures, and quality inspection inside a virtual environment.', (select id from public.media where slug = 'asset-painting'), null, 'xaynvTT2mmQ', 11),
('uno-minda-pdi-inspection', 'UNO Minda PDI Inspection', 'A VR training module for Pre-Delivery Inspection (PDI) that helps users learn inspection procedures, defect detection, and quality verification for casting components.', (select id from public.media where slug = 'asset-pdi'), null, 'Ip5nZ9iEM44', 12),
('uno-minda-plug-in-process', 'UNO Minda Plug-In Process', 'An immersive VR simulation where users learn the plug-in assembly process including component placement, alignment, and secure fitting procedures in an industrial workflow.', (select id from public.media where slug = 'asset-plugin'), null, null, 13),
('uno-minda-vmc-operation', 'UNO Minda VMC Operation', 'A virtual reality training simulator that teaches operators how to work with Vertical Machining Centers (VMC), including machine setup, machining workflow, and safety practices.', (select id from public.media where slug = 'asset-vmc'), null, null, 14),
('3d-chess-game', '3D Chess Game', 'Multiplayer 3D chess game using Unity and Blender. Implemented server-client architecture in .NET for online multiplayer and used OOP principles for maintainable code.', (select id from public.media where slug = 'asset-chess'), 'https://github.com/aditya29mishra/3d-chess-game', null, 15),
('tagore-hostel-fps-game', 'Tagore Hostel (FPS Game)', 'Developed a first-person shooting game in Unreal Engine, creating a detailed environment and interactive shooting mechanics.', (select id from public.media where slug = 'asset-tagoreHostel'), null, null, 16),
('plus-one-dimension', '+1 Dimension', 'Built a virtual reality property exploration system with customizable room layouts and AR visualization using marker-based technology.', (select id from public.media where slug = 'asset-plusOneDimension'), null, null, 17),
('spotify-clone', 'Spotify Clone', 'AM Music App is a Kotlin-based music streaming platform using Jetpack Compose, Spotify API integration, and Firebase.', (select id from public.media where slug = 'asset-amMusic'), null, null, 18),
('iit-jodhpur-navigational-mapping', 'IIT Jodhpur Navigational Mapping', 'Developed an AR-based campus navigation system for IIT Jodhpur using Unity, ARCore, and Flutter.', (select id from public.media where slug = 'asset-ihub'), null, null, 19),
('quiz-game', 'Quiz Game', 'Interactive 3D quiz game in Unity using C#, Blender, and Firebase.', (select id from public.media where slug = 'asset-quizGame'), 'https://github.com/aditya29mishra/quiz-Game', null, 20),
('flappy-bird', 'Flappy Bird', '2D mobile game in Unity with custom physics and Firebase leaderboard.', (select id from public.media where slug = 'asset-flappyBird'), 'https://github.com/aditya29mishra/AM-Birdy', null, 21);

insert into public.project_skill_tags (project_id, skill_id, label, sort_order) values
((select id from public.projects where slug = 'driving-simulator'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'driving-simulator'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'driving-simulator'), null, 'VR Development', 2),
((select id from public.projects where slug = 'driving-simulator'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'driving-simulator'), null, 'Vehicle Physics', 4),
((select id from public.projects where slug = 'mr-btech-electronics-training-modules'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'mr-btech-electronics-training-modules'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'mr-btech-electronics-training-modules'), null, 'Mixed Reality', 2),
((select id from public.projects where slug = 'mr-btech-electronics-training-modules'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'mr-btech-electronics-training-modules'), null, 'Educational Simulation', 4),
((select id from public.projects where slug = 'vr-lathe-machine-training'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'vr-lathe-machine-training'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'vr-lathe-machine-training'), null, 'VR Development', 2),
((select id from public.projects where slug = 'vr-lathe-machine-training'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'vr-lathe-machine-training'), null, 'Industrial Simulation', 4),
((select id from public.projects where slug = 'crane-simulator'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'crane-simulator'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'crane-simulator'), null, 'VR Development', 2),
((select id from public.projects where slug = 'crane-simulator'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'crane-simulator'), null, 'Physics Simulation', 4),
((select id from public.projects where slug = 'advanced-vr-welding-simulator'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'advanced-vr-welding-simulator'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'advanced-vr-welding-simulator'), null, 'VR Development', 2),
((select id from public.projects where slug = 'advanced-vr-welding-simulator'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'advanced-vr-welding-simulator'), null, 'Industrial Simulation', 4),
((select id from public.projects where slug = 'fire-safety-training'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'fire-safety-training'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'fire-safety-training'), null, 'VR Development', 2),
((select id from public.projects where slug = 'fire-safety-training'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'fire-safety-training'), null, 'Scripting', 4),
((select id from public.projects where slug = 'screwing-process-training'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'screwing-process-training'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'screwing-process-training'), null, 'VR Development', 2),
((select id from public.projects where slug = 'screwing-process-training'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'screwing-process-training'), null, 'Scripting', 4),
((select id from public.projects where slug = 'terminal-fixing'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'terminal-fixing'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'terminal-fixing'), null, 'VR Development', 2),
((select id from public.projects where slug = 'terminal-fixing'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'terminal-fixing'), null, 'Scripting', 4),
((select id from public.projects where slug = 'holder-fixing'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'holder-fixing'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'holder-fixing'), null, 'VR Development', 2),
((select id from public.projects where slug = 'holder-fixing'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'holder-fixing'), null, 'Scripting', 4),
((select id from public.projects where slug = 'uno-minda-die-casting-training'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'uno-minda-die-casting-training'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'uno-minda-die-casting-training'), null, 'VR Development', 2),
((select id from public.projects where slug = 'uno-minda-die-casting-training'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'uno-minda-die-casting-training'), null, 'Industrial Simulation', 4),
((select id from public.projects where slug = 'uno-minda-leakage-testing'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'uno-minda-leakage-testing'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'uno-minda-leakage-testing'), null, 'VR Development', 2),
((select id from public.projects where slug = 'uno-minda-leakage-testing'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'uno-minda-leakage-testing'), null, 'Industrial Training', 4),
((select id from public.projects where slug = 'uno-minda-painting-process'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'uno-minda-painting-process'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'uno-minda-painting-process'), null, 'VR Development', 2),
((select id from public.projects where slug = 'uno-minda-painting-process'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'uno-minda-painting-process'), null, 'Industrial Simulation', 4),
((select id from public.projects where slug = 'uno-minda-pdi-inspection'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'uno-minda-pdi-inspection'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'uno-minda-pdi-inspection'), null, 'VR Development', 2),
((select id from public.projects where slug = 'uno-minda-pdi-inspection'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'uno-minda-pdi-inspection'), null, 'Industrial Simulation', 4),
((select id from public.projects where slug = 'uno-minda-plug-in-process'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'uno-minda-plug-in-process'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'uno-minda-plug-in-process'), null, 'VR Development', 2),
((select id from public.projects where slug = 'uno-minda-plug-in-process'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'uno-minda-plug-in-process'), null, 'Industrial Training', 4),
((select id from public.projects where slug = 'uno-minda-vmc-operation'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'uno-minda-vmc-operation'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'uno-minda-vmc-operation'), null, 'VR Development', 2),
((select id from public.projects where slug = 'uno-minda-vmc-operation'), null, 'XR Interaction Toolkit', 3),
((select id from public.projects where slug = 'uno-minda-vmc-operation'), null, 'Industrial Simulation', 4),
((select id from public.projects where slug = '3d-chess-game'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = '3d-chess-game'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = '3d-chess-game'), (select id from public.skills where slug = 'blender'), 'Blender', 2),
((select id from public.projects where slug = '3d-chess-game'), (select id from public.skills where slug = 'dot-net'), '.NET', 3),
((select id from public.projects where slug = '3d-chess-game'), null, 'Multiplayer Systems', 4),
((select id from public.projects where slug = 'tagore-hostel-fps-game'), null, 'Unreal Engine', 0),
((select id from public.projects where slug = 'tagore-hostel-fps-game'), (select id from public.skills where slug = 'blender'), 'Blender', 1),
((select id from public.projects where slug = 'tagore-hostel-fps-game'), (select id from public.skills where slug = 'substance-painter'), 'Substance Painter', 2),
((select id from public.projects where slug = 'plus-one-dimension'), null, 'Unreal Engine', 0),
((select id from public.projects where slug = 'plus-one-dimension'), (select id from public.skills where slug = 'blender'), 'Blender', 1),
((select id from public.projects where slug = 'plus-one-dimension'), (select id from public.skills where slug = 'c-sharp'), 'C#', 2),
((select id from public.projects where slug = 'plus-one-dimension'), null, 'Marker-based AR', 3),
((select id from public.projects where slug = 'plus-one-dimension'), null, 'HTML', 4),
((select id from public.projects where slug = 'plus-one-dimension'), null, 'CSS', 5),
((select id from public.projects where slug = 'plus-one-dimension'), (select id from public.skills where slug = 'flutter'), 'Flutter', 6),
((select id from public.projects where slug = 'spotify-clone'), (select id from public.skills where slug = 'kotlin'), 'Kotlin', 0),
((select id from public.projects where slug = 'spotify-clone'), (select id from public.skills where slug = 'firebase'), 'Firebase', 1),
((select id from public.projects where slug = 'spotify-clone'), (select id from public.skills where slug = 'jetpack-compose'), 'Jetpack Compose', 2),
((select id from public.projects where slug = 'spotify-clone'), (select id from public.skills where slug = 'retrofit'), 'Retrofit', 3),
((select id from public.projects where slug = 'spotify-clone'), (select id from public.skills where slug = 'api'), 'API', 4),
((select id from public.projects where slug = 'iit-jodhpur-navigational-mapping'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'iit-jodhpur-navigational-mapping'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'iit-jodhpur-navigational-mapping'), null, 'Android Studio', 2),
((select id from public.projects where slug = 'iit-jodhpur-navigational-mapping'), null, 'ARCore', 3),
((select id from public.projects where slug = 'iit-jodhpur-navigational-mapping'), (select id from public.skills where slug = 'blender'), 'Blender', 4),
((select id from public.projects where slug = 'iit-jodhpur-navigational-mapping'), (select id from public.skills where slug = 'flutter'), 'Flutter', 5),
((select id from public.projects where slug = 'iit-jodhpur-navigational-mapping'), null, 'QR code', 6),
((select id from public.projects where slug = 'quiz-game'), (select id from public.skills where slug = 'unity-3d'), 'Unity 3D', 0),
((select id from public.projects where slug = 'quiz-game'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'quiz-game'), (select id from public.skills where slug = 'blender'), 'Blender', 2),
((select id from public.projects where slug = 'quiz-game'), (select id from public.skills where slug = 'firebase'), 'Firebase', 3),
((select id from public.projects where slug = 'quiz-game'), null, 'OOPs', 4),
((select id from public.projects where slug = 'flappy-bird'), null, 'Unity 2D', 0),
((select id from public.projects where slug = 'flappy-bird'), (select id from public.skills where slug = 'c-sharp'), 'C#', 1),
((select id from public.projects where slug = 'flappy-bird'), (select id from public.skills where slug = 'firebase'), 'Firebase', 2),
((select id from public.projects where slug = 'flappy-bird'), null, 'Mobile Development', 3);

insert into public.timeline_entries (slug, organization_name, entry_type, role_title, tech_stack, summary, date_range, sort_order) values
('elektro-labs-junior-unity-developer', 'ELEKTRO LABs', 'work', 'Junior Unity Developer', 'Unity3D, C#, AR/VR/MR', 'I create VR training modules for DOJO, including Fire Safety Training, Screwing Process Training, Terminal & Holder Fixing, and PDI Training. My responsibilities include programming, designing training flows, and managing client interactions and deployments.', 'Feb 2025 - Present', 0),
('algovation-game-developer-intern', 'Algovation.in', 'work', 'Game Devloper Intern', 'Unity3d, C# ', 'Developing engaging mobile-based games using Unity3D. Focused on optimizing gameplay mechanics, implementing interactive features, and delivering high-quality gaming experiences tailored for mobile platforms.', 'Dec 2024 -  JAN 2025', 1),
('iit-jodhpur-tih-ihub-drishti-intern', 'IIT Jodhpur', 'work', 'Intern at TIH iHUB Drishti', 'Unity, C#, ARCore, Android SDKs', 'Developed high-performance AR/VR software solutions, optimized real-time performance, and collaborated with interdisciplinary teams for interactive XR experiences.', 'July 2024 - Sep 2024', 2),
('aditya-mishra-hackathon-achievements', 'Aditya Mishra', 'work', 'Hackathon Achievements', 'Problem-Solving, AR/VR, Team Collaboration', 'Winner of Kumbh Mela Hackathon (IIITA, 2024), InnoHacks''23 Hackathon, and Innotech''22 KIET annual technical fest.', '2022 - 2024', 3),
('kiet-group-of-institution-btech-computer-science', 'KIET Gruop of institution', 'education', 'B.Tech in Computer Science', null, 'Pursuing final year with a strong focus on Machine Learning, AI, and AR/VR projects. Actively involved in hands-on projects and internships to enhance technical and practical knowledge.', 'Aug 2021 - May 2025', 4);

insert into public.personas (slug, label, avatar_media_id, background_media_id, top_picks_group_key, continue_watching_group_key, sort_order) values
('recruiter', 'recruiter', (select id from public.media where slug = 'asset-blue'), (select id from public.media where slug = 'persona-recruiter-background'), 'recruiter', 'default', 0),
('developer', 'developer', (select id from public.media where slug = 'asset-grey'), (select id from public.media where slug = 'persona-developer-background'), 'developer', 'default', 1),
('stalker', 'stalker', (select id from public.media where slug = 'asset-red'), (select id from public.media where slug = 'persona-stalker-background'), 'stalker', 'stalker', 2),
('adventurer', 'adventurer', (select id from public.media where slug = 'asset-yellow'), (select id from public.media where slug = 'persona-adventurer-background'), 'adventurer', 'default', 3);

insert into public.persona_recommendations (slot_group, recommendation_group_key, title, route, icon_key, media_id, sort_order) values
('top_picks', 'recruiter', 'Skills', '/skills', 'FaCode', (select id from public.media where slug = 'recommendation-top_picks-recruiter-0'), 0),
('top_picks', 'recruiter', 'Experience', '/work-experience', 'FaBriefcase', (select id from public.media where slug = 'recommendation-top_picks-recruiter-1'), 1),
('top_picks', 'recruiter', 'Projects', '/projects', 'FaProjectDiagram', (select id from public.media where slug = 'recommendation-top_picks-recruiter-2'), 2),
('top_picks', 'recruiter', 'Contact Me', '/contact-me', 'FaEnvelope', (select id from public.media where slug = 'recommendation-top_picks-recruiter-3'), 3),
('top_picks', 'recruiter', 'Let''s Play', '/game/recruiter', 'FaGamepad', (select id from public.media where slug = 'recommendation-top_picks-recruiter-4'), 4),
('top_picks', 'developer', 'Skills', '/skills', 'FaCode', (select id from public.media where slug = 'recommendation-top_picks-developer-0'), 0),
('top_picks', 'developer', 'Projects', '/projects', 'FaProjectDiagram', (select id from public.media where slug = 'recommendation-top_picks-developer-1'), 1),
('top_picks', 'developer', 'Experience', '/work-experience', 'FaBriefcase', (select id from public.media where slug = 'recommendation-top_picks-developer-2'), 2),
('top_picks', 'developer', 'Contact Me', '/contact-me', 'FaEnvelope', (select id from public.media where slug = 'recommendation-top_picks-developer-3'), 3),
('top_picks', 'developer', 'Let''s Play', '/game/developer', 'FaGamepad', (select id from public.media where slug = 'recommendation-top_picks-developer-4'), 4),
('top_picks', 'stalker', 'Contact Me', '/contact-me', 'FaEnvelope', (select id from public.media where slug = 'recommendation-top_picks-stalker-0'), 0),
('top_picks', 'stalker', 'Projects', '/projects', 'FaProjectDiagram', (select id from public.media where slug = 'recommendation-top_picks-stalker-1'), 1),
('top_picks', 'stalker', 'Experience', '/work-experience', 'FaBriefcase', (select id from public.media where slug = 'recommendation-top_picks-stalker-2'), 2),
('top_picks', 'stalker', 'Let''s Play', '/game/stalker', 'FaGamepad', (select id from public.media where slug = 'recommendation-top_picks-stalker-3'), 3),
('top_picks', 'adventurer', 'Music', '/music', 'FaMusic', (select id from public.media where slug = 'recommendation-top_picks-adventurer-0'), 0),
('top_picks', 'adventurer', 'Projects', '/projects', 'FaProjectDiagram', (select id from public.media where slug = 'recommendation-top_picks-adventurer-1'), 1),
('top_picks', 'adventurer', 'Reading', '/reading', 'FaBook', (select id from public.media where slug = 'recommendation-top_picks-adventurer-2'), 2),
('top_picks', 'adventurer', 'Contact Me', '/contact-me', 'FaEnvelope', (select id from public.media where slug = 'recommendation-top_picks-adventurer-3'), 3),
('top_picks', 'adventurer', 'Let''s Play', '/game/adventure', 'FaGamepad', (select id from public.media where slug = 'recommendation-top_picks-adventurer-4'), 4),
('continue_watching', 'default', 'Music', '/music', null, (select id from public.media where slug = 'recommendation-continue_watching-default-0'), 0),
('continue_watching', 'default', 'Reading', '/reading', null, (select id from public.media where slug = 'recommendation-continue_watching-default-1'), 1),
('continue_watching', 'default', 'Contact Me', '/contact-me', null, (select id from public.media where slug = 'recommendation-continue_watching-default-2'), 2),
('continue_watching', 'stalker', 'Reading', '/reading', null, (select id from public.media where slug = 'recommendation-continue_watching-stalker-0'), 0),
('continue_watching', 'stalker', 'Contact Me', '/contact-me', null, (select id from public.media where slug = 'recommendation-continue_watching-stalker-1'), 1);

insert into public.content_items (section, item_type, slug, title, subtitle, description, embed_url, media_id, sort_order) values
('reading', 'book', 'atomic-habits', 'Atomic Habits', 'James Clear', 'An Easy & Proven Way to Build Good Habits & Break Bad Ones.', null, (select id from public.media where slug = 'asset-atomicHabits'), 0),
('reading', 'book', 'rich-dad-poor-dad', 'Rich Dad Poor Dad', 'Robert Kiyosaki', 'What the Rich Teach Their Kids About Money.', null, (select id from public.media where slug = 'asset-richDadPoorDad'), 1),
('reading', 'book', 'a-song-of-ice-and-fire', 'A Song of Ice and Fire', 'George R.R. Martin', 'FIRE AND BLOOD is the definitive history of the Targaryens in Westeros.', null, (select id from public.media where slug = 'asset-songOfIceAndFire'), 2),
('reading', 'book', 'harry-potter', 'Harry Potter', 'J.K. Rowling', 'Harry dreams he will win the competition.', null, (select id from public.media where slug = 'asset-harryPotter'), 3),
('music', 'song', 'song-1', null, null, null, 'https://open.spotify.com/embed/track/5W7DOVGQLTigu09afW7QMT?utm_source=generator', null, 0),
('music', 'song', 'song-2', null, null, null, 'https://open.spotify.com/embed/track/1dGr1c8CrMLDpV6mPbImSI?utm_source=generator', null, 1),
('music', 'song', 'song-3', null, null, null, 'https://open.spotify.com/embed/track/7fBv7CLKzipRk6EC6TWHOB?utm_source=generator', null, 2),
('music', 'collection', 'top-50-global', 'Top 50 Global', null, 'Today''s most popular tracks from across the globe.', 'https://open.spotify.com/embed/playlist/37i9dQZEVXbMDoHDwVN2tF?utm_source=generator', null, 3),
('music', 'collection', 'my-top-songs-2023', 'My Top Songs 2023', null, 'Your most played songs of 2023.', 'https://open.spotify.com/embed/playlist/37i9dQZF1Fa1IIVtEpGUcU?utm_source=generator', null, 4),
('music', 'collection', 'moonchild-era-diljit-dosanjh', 'Moonchild Era - Diljit Dosanjh', null, 'An album by Diljit Dosanjh full of soulful tracks.', 'https://open.spotify.com/embed/album/0wkGNaTXbbxaD9QjvxlNGE?utm_source=generator', null, 5);

commit;
