const skillsData = [
    {
      name: "Unity 3D",
      category: "Game Development",
      description: "A versatile platform for creating 3D and 2D games.",
      icon: "FaGamepad",
    },
    {
      name: "C#",
      category: "Programming Languages",
      description: "A powerful language for building games and applications.",
      icon: "FaCode",
    },
    {
      name: "Kotlin",
      category: "Mobile Development",
      description: "A modern language for Android app development.",
      icon: "FaAndroid",
    },
    {
      name: "API",
      category: "Mobile Development",
      description: "Integrating third-party services for enhanced app functionality.",
      icon: "FaNetworkWired",
    },
    {
      name: "Jetpack Compose",
      category: "Mobile Development",
      description: "A modern toolkit for building native Android UIs.",
      icon: "FaAndroid",
    },
    {
      name: "ExoPlayer",
      category: "Mobile Development",
      description: "A media playback library for Android.",
      icon: "FaPlayCircle",
    },
    {
      name: "Retrofit",
      category: "Mobile Development",
      description: "A type-safe HTTP client for Android.",
      icon: "FaNetworkWired",
    },
    {
      name: "Firebase",
      category: "Mobile Development",
      description: "A suite of tools for app development and analytics.",
      icon: "FaCloud",
    },
    {
      name: "Hilt",
      category: "Mobile Development",
      description: "A dependency injection library for Android apps.",
      icon: "FaTools",
    },
    {
      name: "Paging 3",
      category: "Mobile Development",
      description: "A library for efficient data loading in Android apps.",
      icon: "FaStream",
    },
    {
      name: "Blender",
      category: "3D Modeling",
      description: "A 3D modeling and animation software.",
      icon: "FaCube",
    },
    {
      name: "Substance Painter",
      category: "3D Modeling",
      description: "A texturing tool for 3D assets.",
      icon: "FaPalette",
    },
    {
      name: ".NET",
      category: "Software Development",
      description: "A framework for building robust backend applications.",
      icon: "FaWindows",
    },
    {
      name: " Unity Netcode",
      category: "Game Development",
      description: "Designing games that support multiple players.",
      icon: "FaUsers",
    },
    {
      name: "Server-Client",
      category: "Software Development",
      description: "Designing robust server-client communication models.",
      icon: "FaServer",
    },
    {
      name: "AWS",
      category: "Software Development",
      description: "Amazon Web Services for scalable cloud solutions.",
      icon: "FaCloud",
    },
    {
      name: "XR Interactions",
      category: "Game Development",
      description: "Creating immersive XR experiences.",
      icon: "FaVrCardboard",
    },
    {
      name: "VR Mechanics",
      category: "Game Development",
      description: "Designing mechanics for virtual reality environments.",
      icon: "FaVrCardboard",
    },
    {
      name: "Figma Canva",
      category: "Tools",
      description: "Creating intuitive and engaging user interfaces.",
      icon: "FaPencilRuler",
    },
    {
      name: "Coroutines",
      category: "Mobile Development",
      description: "Efficiently managing asynchronous tasks in Kotlin.",
      icon: "FaClock",
    },
    {
      name: "Game Mechanics",
      category: "Game Development",
      description: "Designing engaging and interactive gameplay mechanics.",
      icon: "FaGamepad",
    },
    {
      name: "Git & GitHub",
      category: "Tools",
      description: "Version control and collaboration tools.",
      icon: "FaGithub",
    },
    {
      name: "HTML & CSS",
      category: "Web Development",
      description: "Building responsive and accessible web pages.",
      icon: "FaHtml5",
    },
    {
        name: "Three.js",
        category: "Web Development",
        description: "Experience in creating 3D web applications using Three.js.",
        icon: "FaCube",
    },
    {
      name: "React",
      category: "Web Development",
      description: "A JavaScript library for building user interfaces.",
      icon: "FaReact",
    },
    {
      name: "JavaScript",
      category: "Programming Languages",
      description: "A versatile language for building web applications.",
      icon: "FaJs",
    },
    {
        name: "Python",
        category: "Programming Languages",
        description: "Extensive experience in machine learning, data analysis, and scripting.",
        icon: "FaPython",
      },
      {
        name: "C++",
        category: "Programming Languages",
        description: "Used for high-performance applications and competitive programming.",
        icon: "FaCode",
      },
      {
        name: "C",
        category: "Programming Languages",
        description: "Foundation of programming with experience in systems development.",
        icon: "FaCuttlefish",
      },
      {
        name: "Flutter",
        category: "Mobile Development",
        description: "Proficient in building cross-platform applications using Flutter",
        icon: "FaMobileAlt",
      },
      {
        name: "Dart",
        category: "Programming Languages",
        description: "Used alongside Flutter for efficient app development",
        icon: "FaCode",
      },
      {
        name: "Netlify",
        category: "Software Development",
        description: "Frontend Deployment Platform",
        icon: "FaCode",
      }
  ];
  
  export default skillsData;
  